const PLAYLISTS=['Nepal.m3u','india.m3u'];
const $=s=>document.querySelector(s),video=$('#video'),list=$('#channelList'),cats=$('#categories'),search=$('#searchInput'),overlay=$('#playerOverlay'),status=$('#playerStatus');
let allChannels=[],activeCategory='all',activeChannel=null,hls=null,showMode='all',tvMode=false;
const favorites=new Set(JSON.parse(localStorage.getItem('laxmanIptvFavorites')||'[]')),recent=JSON.parse(localStorage.getItem('laxmanIptvRecent')||'[]');
const categoryName=f=>f.replace(/\.m3u$/i,'').replace(/[-_]+/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
const esc=s=>String(s).replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
function parseM3U(text,file){const l=text.split(/\r?\n/),o=[];for(let i=0;i<l.length;i++){if(!l[i].trim().startsWith('#EXTINF'))continue;const info=l[i].trim(),url=(l[i+1]||'').trim();if(!url||url.startsWith('#'))continue;const p=info.indexOf(','),name=p>-1?info.slice(p+1).trim():'Unknown Channel',logo=(info.match(/tvg-logo="([^"]*)"/i)||[])[1]||'',group=(info.match(/group-title="([^"]*)"/i)||[])[1]||categoryName(file);o.push({id:`${file}:${i}`,name,url,logo,group,source:file,category:categoryName(file)})}return o}
async function loadAll(){list.innerHTML='<div class="empty">Loading all Nepal & India channels…</div>';$('#channelRows').innerHTML='<div class="rows-empty">Loading channel rows…</div>';try{const results=await Promise.allSettled(PLAYLISTS.map(async f=>{const x=await fetch(f,{cache:'no-store'});if(!x.ok)throw Error(`${f}: HTTP ${x.status}`);return parseM3U(await x.text(),f)}));const loaded=results.filter(x=>x.status==='fulfilled').map(x=>x.value);const failed=results.filter(x=>x.status==='rejected').map(x=>x.reason?.message||'Unknown playlist');const seen=new Set();allChannels=loaded.flat().filter(c=>{const k=c.name.toLowerCase()+'|'+c.url;if(seen.has(k))return false;seen.add(k);return true});renderCategories();renderChannels();renderRows();$('#channelCount').textContent=allChannels.length;$('#categoryCount').textContent=PLAYLISTS.filter((_,i)=>results[i].status==='fulfilled').length;if(failed.length)console.warn('Skipped playlists:',failed);if(!allChannels.length){list.innerHTML='<div class="empty">No channels were found in Nepal.m3u or india.m3u.</div>';$('#channelRows').innerHTML='<div class="rows-empty">No channels available.</div>'}const last=localStorage.getItem('laxmanIptvLast'),c=allChannels.find(x=>x.id===last);if(c)updateNow(c)}catch(e){console.error(e);list.innerHTML='<div class="empty">Could not load Nepal.m3u / india.m3u.</div>';$('#channelRows').innerHTML='<div class="rows-empty">Could not load channel rows.</div>'}$('#visibleCount').textContent=`${allChannels.length} channels loaded`}
function renderCategories(){cats.innerHTML='';[['all','All Channels'],['favorites','☆ Favorites'],...PLAYLISTS.map(f=>[f,categoryName(f)])].forEach(([id,label])=>{const b=document.createElement('button');b.className=`cat ${activeCategory===id?'active':''}`;b.textContent=label;b.onclick=()=>{activeCategory=id;showMode='all';renderCategories();renderChannels()};cats.appendChild(b)})}
function getVisible(){const q=search.value.trim().toLowerCase();let a=allChannels.filter(c=>(activeCategory==='all'||activeCategory==='favorites'||c.source===activeCategory)&&(!q||c.name.toLowerCase().includes(q)||c.group.toLowerCase().includes(q)));if(activeCategory==='favorites'||showMode==='favorites')a=a.filter(c=>favorites.has(c.id));if(showMode==='recent')a=recent.map(id=>allChannels.find(c=>c.id===id)).filter(Boolean);return a}
function logo(c,cls='channel-logo'){return c.logo?`<img class="${cls}" src="${esc(c.logo)}" alt="" loading="lazy" onerror="this.outerHTML='<div class="${cls} fallback">TV</div>'">`:`<div class="${cls} fallback">TV</div>`}
function renderChannels(){const a=getVisible(),title=showMode==='favorites'||activeCategory==='favorites'?'Favorites':showMode==='recent'?'Recently Watched':activeCategory==='all'?'All Channels':categoryName(activeCategory);$('#listTitle').textContent=title;$('#visibleCount').textContent=`${a.length} channel${a.length===1?'':'s'}`;if(!a.length){list.innerHTML='<div class="empty">No channels found.</div>';return}const f=document.createDocumentFragment();a.forEach(c=>{const b=document.createElement('button');b.className=`channel ${activeChannel?.id===c.id?'active':''}`;b.dataset.id=c.id;b.innerHTML=`${logo(c)}<div class="channel-info"><strong>${esc(c.name)}</strong><span>${esc(c.group||c.category)} · ${esc(c.source.replace('.m3u',''))}</span></div><span class="heart ${favorites.has(c.id)?'on':''}">${favorites.has(c.id)?'★':'☆'}</span>`;b.onclick=()=>play(c);f.appendChild(b)});list.replaceChildren(f);if(tvMode)focusActive()}
function rowCard(c){const b=document.createElement('button');b.className=`row-card ${activeChannel?.id===c.id?'active':''}`;b.dataset.id=c.id;b.innerHTML=`<div class="row-logo-wrap">${logo(c,'row-logo')}<span class="row-live">LIVE</span></div><strong>${esc(c.name)}</strong><span>${esc(c.group||c.category)}</span>`;b.onclick=()=>play(c);b.onfocus=()=>b.scrollIntoView({behavior:'smooth',block:'nearest',inline:'center'});return b}
function addRow(title,items,key,options={}){if(!items.length)return;const section=document.createElement('section');section.className='channel-row';section.dataset.row=key;const head=document.createElement('div');head.className='row-head';head.innerHTML=`<div><h3>${esc(title)}</h3><span>${items.length} channel${items.length===1?'':'s'}</span></div><button class="row-view" data-row-key="${esc(key)}">View all ›</button>`;const rail=document.createElement('div');rail.className='row-rail';rail.setAttribute('role','list');items.slice(0,30).forEach(c=>{const card=rowCard(c);card.setAttribute('role','listitem');rail.appendChild(card)});section.append(head,rail);head.querySelector('.row-view').onclick=()=>{activeCategory=options.source||'all';showMode=options.mode||'all';renderCategories();renderChannels();document.querySelector('.channel-panel')?.scrollIntoView({behavior:'smooth',block:'start'})};$('#channelRows').appendChild(section)}
function renderRows(){const root=$('#channelRows');root.innerHTML='';const q=search.value.trim();const recentItems=recent.map(id=>allChannels.find(c=>c.id===id)).filter(Boolean);const favItems=allChannels.filter(c=>favorites.has(c.id));if(q){addRow(`Search results for “${q}”`,getVisible(),'search',{source:'all'});return}addRow('Continue Watching',recentItems,'recent',{mode:'recent'});addRow('My Favorites',favItems,'favorites',{mode:'favorites'});PLAYLISTS.forEach(file=>addRow(categoryName(file),allChannels.filter(c=>c.source===file),file,{source:file}));if(!root.children.length)root.innerHTML='<div class="rows-empty">No channels are available yet.</div>'}
function showOverlay(m,spin=true){overlay.classList.remove('hidden');status.textContent=m;overlay.querySelector('.spinner').style.display=spin?'block':'none'}
function updateNow(c){activeChannel=c;$('#nowTitle').textContent=c.name;$('#nowMeta').textContent=`${c.category} · ${c.group||'Live stream'}`;$('#nowAvatar').textContent=(c.name.match(/[A-Za-z0-9]/)?.[0]||'TV').toUpperCase();$('#favoriteBtn').textContent=favorites.has(c.id)?'★':'☆';localStorage.setItem('laxmanIptvLast',c.id)}
function addRecent(id){recent.splice(0,recent.length,...[id,...recent.filter(x=>x!==id)].slice(0,20));localStorage.setItem('laxmanIptvRecent',JSON.stringify(recent))}
function toggleFavorite(c){if(!c)return;favorites.has(c.id)?favorites.delete(c.id):favorites.add(c.id);localStorage.setItem('laxmanIptvFavorites',JSON.stringify([...favorites]));updateNow(c);renderChannels();renderRows()}
function play(c){updateNow(c);addRecent(c.id);renderChannels();renderRows();showOverlay('Connecting…');if(hls){hls.destroy();hls=null}video.pause();video.removeAttribute('src');video.load();if(window.Hls&&Hls.isSupported()){hls=new Hls({enableWorker:true,lowLatencyMode:true,maxBufferLength:18,backBufferLength:20,capLevelToPlayerSize:true,maxLiveSyncPlaybackRate:1.2,liveSyncDurationCount:3});hls.loadSource(c.url);hls.attachMedia(video);hls.on(Hls.Events.MANIFEST_PARSED,startPlayback);hls.on(Hls.Events.ERROR,(_,d)=>{if(d.fatal){if(d.type===Hls.ErrorTypes.NETWORK_ERROR){showOverlay('Network issue — retrying…');setTimeout(()=>hls?.startLoad(),1200)}else showOverlay('Playback error',false)}})}else if(video.canPlayType('application/vnd.apple.mpegurl')){video.src=c.url;video.addEventListener('loadedmetadata',startPlayback,{once:true})}else showOverlay('HLS is not supported',false);if(!tvMode)$('#playerShell').scrollIntoView({behavior:'smooth',block:'start'})}
async function startPlayback(){try{await video.play();overlay.classList.add('hidden')}catch(e){status.textContent='Press play to start';overlay.querySelector('.spinner').style.display='none'}}
function moveChannel(d){const a=getVisible();if(!a.length)return;let i=a.findIndex(c=>c.id===activeChannel?.id);play(a[(i<0?0:i+d+a.length)%a.length])}
function focusActive(){const x=[...list.querySelectorAll('.channel')].find(b=>b.classList.contains('active'))||list.querySelector('.channel');x?.focus({preventScroll:true})}
function toggleTVMode(){tvMode=!tvMode;document.body.classList.toggle('tv-mode',tvMode);$('#tvModeBtn').textContent=tvMode?'▣ Exit TV':'▣ TV Mode';if(tvMode){document.documentElement.requestFullscreen?.().catch(()=>{});focusActive()}else if(document.fullscreenElement)document.exitFullscreen().catch(()=>{})}
video.addEventListener('waiting',()=>activeChannel&&showOverlay('Buffering…'));video.addEventListener('playing',()=>overlay.classList.add('hidden'));video.addEventListener('error',()=>activeChannel&&showOverlay('Unable to play this stream',false));video.addEventListener('ended',()=>moveChannel(1));
search.addEventListener('input',()=>{showMode='all';renderChannels();renderRows()});$('#refreshBtn').onclick=loadAll;$('#favoritesBtn').onclick=()=>{showMode=showMode==='favorites'?'all':'favorites';renderChannels();renderRows()};$('#recentBtn').onclick=()=>{showMode=showMode==='recent'?'all':'recent';renderChannels();renderRows()};$('#favoriteBtn').onclick=()=>toggleFavorite(activeChannel);$('#prevBtn').onclick=()=>moveChannel(-1);$('#nextBtn').onclick=()=>moveChannel(1);$('#pipBtn').onclick=async()=>{try{document.pictureInPictureElement?await document.exitPictureInPicture():await video.requestPictureInPicture()}catch(e){}};$('#fullscreenBtn').onclick=()=>document.fullscreenElement?document.exitFullscreen():$('#playerShell').requestFullscreen?.();$('#themeBtn').onclick=()=>document.body.classList.toggle('light');
const tvBtn=document.createElement('button');tvBtn.id='tvModeBtn';tvBtn.className='small-btn tv-mode-btn';tvBtn.textContent='▣ TV Mode';$('.toolbar-actions').prepend(tvBtn);tvBtn.onclick=toggleTVMode;
document.querySelectorAll('.mobile-nav button').forEach(b=>b.onclick=()=>{const n=b.dataset.nav;if(n==='top')scrollTo({top:0,behavior:'smooth'});if(n==='player')$('#playerShell').scrollIntoView({behavior:'smooth'});if(n==='favorites'){showMode='favorites';renderChannels();renderRows();$('#channelList').scrollIntoView({behavior:'smooth'})}if(n==='categories')$('#categories').scrollIntoView({behavior:'smooth'});document.querySelectorAll('.mobile-nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active')});
document.addEventListener('keydown',e=>{if(e.target.matches('input'))return;if(e.key==='Escape'&&tvMode){toggleTVMode();return}if(['ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();moveChannel(e.key==='ArrowUp'?-1:1)}if(e.key==='ArrowLeft'&&tvMode){e.preventDefault();moveChannel(-1)}if(e.key==='ArrowRight'&&tvMode){e.preventDefault();moveChannel(1)}if(e.key==='Enter'&&tvMode&&document.activeElement?.classList.contains('channel')){e.preventDefault();document.activeElement.click()}if(e.key===' '){e.preventDefault();video.paused?video.play():video.pause()}if(e.key.toLowerCase()==='f')$('#fullscreenBtn').click();if(e.key.toLowerCase()==='m')video.muted=!video.muted;if(e.key.toLowerCase()==='t')toggleTVMode();if(e.key.toLowerCase()==='l')toggleFavorite(activeChannel)});
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));
loadAll();