const PLAYLISTS=['Nepal.m3u','india.m3u'];
const $=s=>document.querySelector(s),video=$('#video'),list=$('#channelList'),cats=$('#categories'),search=$('#searchInput'),overlay=$('#playerOverlay'),status=$('#playerStatus');
let allChannels=[],activeCategory='all',activeChannel=null,hls=null,showMode='all',tvMode=false,loadToken=0,visibleLimit=50,visibleItems=[],playToken=0,preload=null;
const favorites=new Set(JSON.parse(localStorage.getItem('laxmanIptvFavorites')||'[]')),recent=JSON.parse(localStorage.getItem('laxmanIptvRecent')||'[]');
window.__iptvChannels=allChannels;window.__iptvPlay=c=>play(c);
const categoryName=f=>f.replace(/\.m3u$/i,'').replace(/[-_]+/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
const esc=s=>String(s).replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
function parseM3U(text,file){const lines=text.split(/\r?\n/),out=[];for(let i=0;i<lines.length;i++){const info=lines[i].trim();if(!info.toUpperCase().startsWith('#EXTINF'))continue;let j=i+1;while(j<lines.length&&!lines[j].trim()&&!lines[j].trim().startsWith('#'))j++;const url=(lines[j]||'').trim();if(!url||url.startsWith('#'))continue;const comma=info.indexOf(',');const name=comma>-1?info.slice(comma+1).trim():'Unknown Channel';const logo=(info.match(/tvg-logo=["']([^"']*)["']/i)||[])[1]||'';const group=(info.match(/group-title=["']([^"']*)["']/i)||[])[1]||categoryName(file);out.push({id:`${file}:${i}`,name:name||'Unknown Channel',url,logo,group,source:file,category:categoryName(file)});i=j-1}return out}
async function fetchPlaylist(file,token){const r=await fetch(file,{cache:'no-store'});if(!r.ok)throw new Error(`${file}: HTTP ${r.status}`);const text=await r.text();if(token!==loadToken)throw new Error('stale load');const channels=parseM3U(text,file);if(!channels.length)throw new Error(`${file}: no channels parsed`);return channels}
async function loadAll(){const token=++loadToken;list.innerHTML='<div class="empty">Loading Nepal + India channels…</div>';$('#channelRows').innerHTML='<div class="rows-empty">Loading channel rows…</div>';$('#visibleCount').textContent='Fetching playlists';const results=await Promise.allSettled(PLAYLISTS.map(f=>fetchPlaylist(f,token)));if(token!==loadToken)return;const loaded=results.filter(r=>r.status==='fulfilled').flatMap(r=>r.value);const failed=results.filter(r=>r.status==='rejected').map(r=>r.reason?.message||'Unknown playlist');const seen=new Set();allChannels=loaded.filter(c=>{const k=`${c.name.toLowerCase()}|${c.url}`;if(seen.has(k))return false;seen.add(k);return true});window.__iptvChannels=allChannels;window.dispatchEvent(new CustomEvent('iptv:channels-ready',{detail:{count:allChannels.length}}));renderCategories();resetVirtualList();renderChannels();renderRows();$('#channelCount').textContent=allChannels.length;$('#categoryCount').textContent=results.filter(r=>r.status==='fulfilled').length;$('#visibleCount').textContent=`${allChannels.length} channels loaded`;if(failed.length)console.warn('Skipped playlists:',failed);if(!allChannels.length){list.innerHTML=`<div class="empty">No channels could be loaded.<br><small>${esc(failed.join(' · ')||'Check the playlist files and GitHub Pages deployment.')}</small></div>`;return}const last=localStorage.getItem('laxmanIptvLast'),c=allChannels.find(x=>x.id===last);if(c)updateNow(c)}
function renderCategories(){cats.innerHTML='';[['all','All Channels'],['favorites','☆ Favorites'],...PLAYLISTS.map(f=>[f,categoryName(f)])].forEach(([id,label])=>{const b=document.createElement('button');b.className=`cat ${activeCategory===id?'active':''}`;b.textContent=label;b.onclick=()=>{activeCategory=id;showMode='all';resetVirtualList();renderCategories();renderChannels()};cats.appendChild(b)})}
function getVisible(){const q=search.value.trim().toLowerCase();let a=allChannels.filter(c=>(activeCategory==='all'||activeCategory==='favorites'||c.source===activeCategory)&&(!q||c.name.toLowerCase().includes(q)||c.group.toLowerCase().includes(q)));if(activeCategory==='favorites'||showMode==='favorites')a=a.filter(c=>favorites.has(c.id));if(showMode==='recent')a=recent.map(id=>allChannels.find(c=>c.id===id)).filter(Boolean);return a}
function logo(c,cls='channel-logo'){return c.logo?`<img class="${cls}" src="${esc(c.logo)}" alt="" loading="lazy" decoding="async" onerror="this.outerHTML='<div class="${cls} fallback">TV</div>'>`:`<div class="${cls} fallback">TV</div>`}
function resetVirtualList(){visibleLimit=50;visibleItems=[]}
function renderChannels(){const a=getVisible();visibleItems=a;const title=showMode==='favorites'||activeCategory==='favorites'?'Favorites':showMode==='recent'?'Recently Watched':activeCategory==='all'?'All Channels':categoryName(activeCategory);$('#listTitle').textContent=title;$('#visibleCount').textContent=a.length>visibleLimit?`Showing ${Math.min(visibleLimit,a.length)} of ${a.length} channels`:`${a.length} channel${a.length===1?'':'s'}`;list.innerHTML='';if(!a.length){list.innerHTML='<div class="empty">No channels found.</div>';return}appendChannelBatch();if(tvMode)focusActive()}
function appendChannelBatch(){const end=Math.min(visibleLimit,visibleItems.length);const f=document.createDocumentFragment();for(let i=list.querySelectorAll('.channel').length;i<end;i++){const c=visibleItems[i],b=document.createElement('button');b.className=`channel ${activeChannel?.id===c.id?'active':''}`;b.dataset.id=c.id;b.innerHTML=`${logo(c)}<div class="channel-info"><strong>${esc(c.name)}</strong><span>${esc(c.group||c.category)} · ${esc(c.source.replace('.m3u',''))}</span></div><span class="stream-state" aria-label="Stream status">●</span><span class="heart ${favorites.has(c.id)?'on':''}">${favorites.has(c.id)?'★':'☆'}</span>`;b.onclick=()=>play(c);f.appendChild(b)}list.appendChild(f);updateLoadMore()}
function updateLoadMore(){list.querySelector('.load-more')?.remove();const count=list.querySelectorAll('.channel').length;if(count<visibleItems.length){const b=document.createElement('button');b.className='load-more';b.textContent=`Load more · ${count} / ${visibleItems.length}`;b.onclick=()=>{visibleLimit+=50;appendChannelBatch()};list.appendChild(b)}}
function rowCard(c){const b=document.createElement('button');b.className=`row-card ${activeChannel?.id===c.id?'active':''}`;b.dataset.id=c.id;b.innerHTML=`<div class="row-logo-wrap">${logo(c,'row-logo')}<span class="row-live">LIVE</span></div><strong>${esc(c.name)}</strong><span>${esc(c.group||c.category)}</span>`;b.onclick=()=>play(c);b.onfocus=()=>b.scrollIntoView({behavior:'smooth',block:'nearest',inline:'center'});return b}
function addRow(title,items,key,options={}){if(!items.length)return;const section=document.createElement('section');section.className='channel-row';section.dataset.row=key;const head=document.createElement('div');head.className='row-head';head.innerHTML=`<div><h3>${esc(title)}</h3><span>${items.length} channel${items.length===1?'':'s'}</span></div><button class="row-view" data-row-key="${esc(key)}">View all ›</button>`;const rail=document.createElement('div');rail.className='row-rail';items.slice(0,40).forEach(c=>{const card=rowCard(c);card.setAttribute('role','listitem');rail.appendChild(card)});section.append(head,rail);head.querySelector('.row-view').onclick=()=>{activeCategory=options.source||'all';showMode=options.mode||'all';resetVirtualList();renderCategories();renderChannels();document.querySelector('.channel-panel')?.scrollIntoView({behavior:'smooth',block:'start'})};$('#channelRows').appendChild(section)}
function renderRows(){const root=$('#channelRows');root.innerHTML='';const q=search.value.trim();const recentItems=recent.map(id=>allChannels.find(c=>c.id===id)).filter(Boolean);const favItems=allChannels.filter(c=>favorites.has(c.id));if(q){addRow(`Search results for “${q}”`,getVisible(),'search',{source:'all'});return}addRow('Continue Watching',recentItems,'recent',{mode:'recent'});addRow('My Favorites',favItems,'favorites',{mode:'favorites'});PLAYLISTS.forEach(file=>addRow(categoryName(file),allChannels.filter(c=>c.source===file),file,{source:file}));if(!root.children.length)root.innerHTML='<div class="rows-empty">No channels are available yet.</div>'}
function showOverlay(m,spin=true){overlay.classList.remove('hidden');status.textContent=m;overlay.querySelector('.spinner').style.display=spin?'block':'none'}
function updateNow(c){activeChannel=c;$('#nowTitle').textContent=c.name;$('#nowMeta').textContent=`${c.category} · ${c.group||'Live stream'}`;$('#nowAvatar').textContent=(c.name.match(/[A-Za-z0-9]/)?.[0]||'TV').toUpperCase();$('#favoriteBtn').textContent=favorites.has(c.id)?'★':'☆';localStorage.setItem('laxmanIptvLast',c.id)}
function addRecent(id){recent.splice(0,recent.length,...[id,...recent.filter(x=>x!==id)].slice(0,20));localStorage.setItem('laxmanIptvRecent',JSON.stringify(recent))}
function toggleFavorite(c){if(!c)return;favorites.has(c.id)?favorites.delete(c.id):favorites.add(c.id);localStorage.setItem('laxmanIptvFavorites',JSON.stringify([...favorites]));updateNow(c);renderChannels();renderRows()}
function setStreamState(state){if(!activeChannel)return;const b=list.querySelector(`.channel[data-id="${CSS.escape(activeChannel.id)}"] .stream-state`);if(b){b.textContent=state==='live'?'●':state==='buffering'?'◐':'!';b.className=`stream-state ${state}`;b.title=state==='live'?'Playing':state==='buffering'?'Buffering':'Stream error'}}
function destroyPlayer(){if(hls){hls.destroy();hls=null}video.pause();video.removeAttribute('src');video.load()}
async function tryPlay(){try{await video.play();return true}catch(e){return false}}
function prewarm(c){if(!c||!window.Hls||!Hls.isSupported()||preload?.id===c.id)return;try{preload?.hls?.destroy();const p=new Hls({enableWorker:true,lowLatencyMode:true,autoStartLoad:true,startFragPrefetch:true,startLevel:-1,maxBufferLength:3,maxMaxBufferLength:6,backBufferLength:3,capLevelToPlayerSize:true,liveSyncDurationCount:2,liveMaxLatencyDurationCount:4,manifestLoadingTimeOut:6000,fragLoadingTimeOut:6000,fragLoadingMaxRetry:1});const m=document.createElement('video');m.muted=true;preload={id:c.id,hls:p,video:m};p.loadSource(c.url);p.attachMedia(m);setTimeout(()=>{if(preload?.id===c.id){preload.hls.destroy();preload=null}},10000)}catch(e){preload=null}}
function getAdjacent(c){const a=getVisible();const i=a.findIndex(x=>x.id===c.id);return i<0?null:a[(i+1)%a.length]}
function play(c){const token=++playToken;updateNow(c);addRecent(c.id);renderChannels();renderRows();showOverlay('Starting live stream…');setStreamState('connecting');const warm=preload?.id===c.id?preload:null;preload=null;destroyPlayer();video.muted=false;if(window.Hls&&Hls.isSupported()){hls=warm?.hls||new Hls({enableWorker:true,lowLatencyMode:true,autoStartLoad:true,startFragPrefetch:true,startLevel:-1,maxBufferLength:5,maxMaxBufferLength:10,backBufferLength:5,capLevelToPlayerSize:true,maxLiveSyncPlaybackRate:1.5,liveSyncDurationCount:2,liveMaxLatencyDurationCount:5,manifestLoadingTimeOut:7000,fragLoadingTimeOut:7000,fragLoadingMaxRetry:3,fragLoadingRetryDelay:350,levelLoadingMaxRetry:2,levelLoadingRetryDelay:350});hls.attachMedia(video);const start=()=>{if(token!==playToken)return;tryPlay();setStreamState('buffering')};hls.on(Hls.Events.MEDIA_ATTACHED,()=>{if(!warm)hls.loadSource(c.url);start()});hls.on(Hls.Events.MANIFEST_PARSED,start);hls.on(Hls.Events.FRAG_BUFFERED,()=>{if(token===playToken)tryPlay()});hls.on(Hls.Events.ERROR,(_,d)=>{if(token!==playToken)return;if(!d.fatal){if(d.type===Hls.ErrorTypes.NETWORK_ERROR)setStreamState('buffering');return}if(d.type===Hls.ErrorTypes.NETWORK_ERROR){setStreamState('buffering');showOverlay('Reconnecting…');setTimeout(()=>token===playToken&&hls?.startLoad(-1),350)}else if(d.type===Hls.ErrorTypes.MEDIA_ERROR){showOverlay('Recovering stream…');hls?.recoverMediaError()}else{setStreamState('error');showOverlay('Stream unavailable',false)}})}else if(video.canPlayType('application/vnd.apple.mpegurl')){video.src=c.url;video.load();video.addEventListener('loadedmetadata',()=>{setStreamState('buffering');tryPlay()},{once:true})}else showOverlay('HLS is not supported',false);if(!tvMode)$('#playerShell').scrollIntoView({behavior:'smooth',block:'start'});prewarm(getAdjacent(c))}
function moveChannel(d){const a=getVisible();if(!a.length)return;let i=a.findIndex(c=>c.id===activeChannel?.id);play(a[(i<0?0:i+d+a.length)%a.length])}
function focusActive(){const x=[...list.querySelectorAll('.channel')].find(b=>b.classList.contains('active'))||list.querySelector('.channel');x?.focus({preventScroll:true})}
function toggleTVMode(){tvMode=!tvMode;document.body.classList.toggle('tv-mode',tvMode);$('#tvModeBtn').textContent=tvMode?'▣ Exit TV':'▣ TV Mode';if(tvMode){document.documentElement.requestFullscreen?.().catch(()=>{});focusActive()}else if(document.fullscreenElement)document.exitFullscreen().catch(()=>{})}
video.addEventListener('waiting',()=>{if(activeChannel){setStreamState('buffering');showOverlay('Buffering…')}});video.addEventListener('stalled',()=>{if(activeChannel){setStreamState('buffering');showOverlay('Reconnecting…')}});video.addEventListener('playing',()=>{setStreamState('live');overlay.classList.add('hidden')});video.addEventListener('canplay',()=>{if(video.paused)tryPlay()});video.addEventListener('error',()=>activeChannel&&showOverlay('Unable to play this stream',false));video.addEventListener('ended',()=>moveChannel(1));
search.addEventListener('input',()=>{showMode='all';resetVirtualList();renderChannels();renderRows()});$('#refreshBtn').onclick=loadAll;$('#favoritesBtn').onclick=()=>{showMode=showMode==='favorites'?'all':'favorites';resetVirtualList();renderChannels();renderRows()};$('#recentBtn').onclick=()=>{showMode=showMode==='recent'?'all':'recent';resetVirtualList();renderChannels();renderRows()};$('#favoriteBtn').onclick=()=>toggleFavorite(activeChannel);$('#prevBtn').onclick=()=>moveChannel(-1);$('#nextBtn').onclick=()=>moveChannel(1);$('#pipBtn').onclick=async()=>{try{document.pictureInPictureElement?await document.exitPictureInPicture():await video.requestPictureInPicture()}catch(e){}};$('#fullscreenBtn').onclick=()=>document.fullscreenElement?document.exitFullscreen():$('#playerShell').requestFullscreen?.();$('#themeBtn').onclick=()=>document.body.classList.toggle('light');
const tvBtn=document.createElement('button');tvBtn.id='tvModeBtn';tvBtn.className='small-btn tv-mode-btn';tvBtn.textContent='▣ TV Mode';$('.toolbar-actions').prepend(tvBtn);tvBtn.onclick=toggleTVMode;
document.querySelector('.channel-panel')?.addEventListener('scroll',()=>{const nearBottom=list.scrollTop+list.clientHeight>=list.scrollHeight-250;if(nearBottom&&list.querySelectorAll('.channel').length<visibleItems.length){visibleLimit+=50;appendChannelBatch()}});
document.querySelectorAll('.mobile-nav button').forEach(b=>b.onclick=()=>{const n=b.dataset.nav;if(n==='top')scrollTo({top:0,behavior:'smooth'});if(n==='player')$('#playerShell').scrollIntoView({behavior:'smooth'});if(n==='favorites'){showMode='favorites';resetVirtualList();renderChannels();renderRows();$('#channelList').scrollIntoView({behavior:'smooth'})}if(n==='categories')$('#categories').scrollIntoView({behavior:'smooth'});document.querySelectorAll('.mobile-nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active')});
document.addEventListener('keydown',e=>{if(e.target.matches('input'))return;if(e.key==='Escape'&&tvMode){toggleTVMode();return}if(['ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();moveChannel(e.key==='ArrowDown'?1:-1)}if(e.key==='PageDown'){e.preventDefault();moveChannel(1)}if(e.key==='PageUp'){e.preventDefault();moveChannel(-1)}});
loadAll();
