const PLAYLISTS=['Nepal.m3u','SPORT-IPTV-DECEMBER.m3u','Sonylive.m3u','Sonylivnew.m3u','Worldcup.m3u','india.m3u'];
const video=document.querySelector('#video'),list=document.querySelector('#channelList'),cats=document.querySelector('#categories'),search=document.querySelector('#searchInput'),overlay=document.querySelector('#playerOverlay'),status=document.querySelector('#playerStatus');
let allChannels=[],activeCategory='all',activeChannel=null,hls=null,showMode='all';
const favorites=new Set(JSON.parse(localStorage.getItem('laxmanIptvFavorites')||'[]')),recent=JSON.parse(localStorage.getItem('laxmanIptvRecent')||'[]');
const categoryName=f=>f.replace(/\.m3u$/i,'').replace(/[-_]+/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
function esc(s){return String(s).replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]))}
function parseM3U(text,file){const lines=text.split(/\r?\n/),out=[];for(let i=0;i<lines.length;i++){if(!lines[i].startsWith('#EXTINF'))continue;const info=lines[i],url=(lines[i+1]||'').trim();if(!url||url.startsWith('#'))continue;const comma=info.indexOf(','),name=comma>-1?info.slice(comma+1).trim():'Unknown Channel',logo=(info.match(/tvg-logo="([^"]*)"/i)||[])[1]||'',group=(info.match(/group-title="([^"]*)"/i)||[])[1]||categoryName(file);out.push({id:`${file}:${i}`,name,url,logo,group,source:file,category:categoryName(file)})}return out}
async function loadAll(){list.innerHTML='<div class="empty">Loading all channels…</div>';try{const results=await Promise.all(PLAYLISTS.map(async f=>{const r=await fetch(f,{cache:'no-store'});if(!r.ok)throw Error(f);return parseM3U(await r.text(),f)}));const seen=new Set();allChannels=results.flat().filter(c=>{const k=`${c.name.toLowerCase()}|${c.url}`;if(seen.has(k))return false;seen.add(k);return true});renderCategories();renderChannels();renderRail();document.querySelector('#channelCount').textContent=allChannels.length;document.querySelector('#categoryCount').textContent=PLAYLISTS.length;const saved=localStorage.getItem('laxmanIptvLast'),c=allChannels.find(x=>x.id===saved);if(c)updateNow(c)}catch(e){list.innerHTML='<div class="empty">Could not load playlists. Check the M3U files and GitHub Pages.</div>'}document.querySelector('#visibleCount').textContent=`${allChannels.length} channels loaded`}
function renderCategories(){cats.innerHTML='';[['all','All Channels'],['favorites','☆ Favorites'],...PLAYLISTS.map(f=>[f,categoryName(f)])].forEach(([id,label])=>{const b=document.createElement('button');b.className=`cat ${activeCategory===id?'active':''}`;b.textContent=label;b.onclick=()=>{activeCategory=id;showMode='all';renderCategories();renderChannels()};cats.appendChild(b)})}
function getVisible(){const q=search.value.trim().toLowerCase();let a=allChannels.filter(c=>(activeCategory==='all'||activeCategory==='favorites'||c.source===activeCategory)&&(!q||c.name.toLowerCase().includes(q)||c.group.toLowerCase().includes(q)));if(activeCategory==='favorites'||showMode==='favorites')a=a.filter(c=>favorites.has(c.id));if(showMode==='recent')a=recent.map(id=>allChannels.find(c=>c.id===id)).filter(Boolean);return a}
function logo(c,cls='channel-logo'){return c.logo?`<img class="${cls}" src="${esc(c.logo)}" alt="" loading="lazy" onerror="this.outerHTML='<div class=\"${cls} fallback\">TV</div>'">`:`<div class="${cls} fallback">TV</div>`}
function renderChannels(){const a=getVisible(),title=showMode==='favorites'||activeCategory==='favorites'?'Favorites':showMode==='recent'?'Recently Watched':activeCategory==='all'?'All Channels':categoryName(activeCategory);document.querySelector('#listTitle').textContent=title;document.querySelector('#visibleCount').textContent=`${a.length} channel${a.length===1?'':'s'}`;if(!a.length){list.innerHTML='<div class="empty">No channels found.</div>';return}const f=document.createDocumentFragment();a.forEach(c=>{const b=document.createElement('button');b.className=`channel ${activeChannel?.id===c.id?'active':''}`;b.innerHTML=`${logo(c)}<div class="channel-info"><strong>${esc(c.name)}</strong><span>${esc(c.group||c.category)} · ${esc(c.source.replace('.m3u',''))}</span></div><span class="heart ${favorites.has(c.id)?'on':''}">${favorites.has(c.id)?'★':'☆'}</span>`;b.onclick=()=>play(c);f.appendChild(b)});list.replaceChildren(f)}
function renderRail(){const r=document.querySelector('#channelRail');r.innerHTML='';allChannels.slice(0,30).forEach(c=>{const b=document.createElement('button');b.className='rail-card';b.innerHTML=`${logo(c,'rail-logo')}<strong>${esc(c.name)}</strong><span>${esc(c.category)}</span>`;b.onclick=()=>play(c);r.appendChild(b)})}
function showOverlay(m,spin=true){overlay.classList.remove('hidden');status.textContent=m;overlay.querySelector('.spinner').style.display=spin?'block':'none'}
function updateNow(c){activeChannel=c;document.querySelector('#nowTitle').textContent=c.name;document.querySelector('#nowMeta').textContent=`${c.category} · ${c.group||'Live stream'}`;document.querySelector('#nowAvatar').textContent=(c.name.match(/[A-Za-z0-9]/)?.[0]||'TV').toUpperCase();document.querySelector('#favoriteBtn').textContent=favorites.has(c.id)?'★':'☆';localStorage.setItem('laxmanIptvLast',c.id)}
function addRecent(id){const n=[id,...recent.filter(x=>x!==id)].slice(0,20);recent.splice(0,recent.length,...n);localStorage.setItem('laxmanIptvRecent',JSON.stringify(recent))}
function play(c){updateNow(c);addRecent(c.id);renderChannels();showOverlay('Connecting…');if(hls){hls.destroy();hls=null}video.pause();video.removeAttribute('src');video.load();if(window.Hls&&Hls.isSupported()){hls=new Hls({enableWorker:true,lowLatencyMode:true,maxBufferLength:20,backBufferLength:30,capLevelToPlayerSize:true,maxLiveSyncPlaybackRate:1.2});hls.loadSource(c.url);hls.attachMedia(video);hls.on(Hls.Events.MANIFEST_PARSED,startPlayback);hls.on(Hls.Events.ERROR,(_,d)=>{if(d.fatal)showOverlay(d.type===Hls.ErrorTypes.NETWORK_ERROR?'Stream unavailable':'Playback error',false)})}else if(video.canPlayType('application/vnd.apple.mpegurl')){video.src=c.url;video.addEventListener('loadedmetadata',startPlayback,{once:true})}else showOverlay('HLS is not supported in this browser',false);document.querySelector('#playerShell').scrollIntoView({behavior:'smooth',block:'start'})}
async function startPlayback(){try{await video.play();overlay.classList.add('hidden')}catch(e){status.textContent='Press play to start';overlay.querySelector('.spinner').style.display='none'}}
function moveChannel(d){const a=getVisible();if(!a.length)return;let i=a.findIndex(c=>c.id===activeChannel?.id);i=(i<0?0:i+d+a.length)%a.length;play(a[i])}
video.addEventListener('waiting',()=>activeChannel&&showOverlay('Buffering…'));video.addEventListener('playing',()=>overlay.classList.add('hidden'));video.addEventListener('error',()=>activeChannel&&showOverlay('Unable to play this stream',false));
search.addEventListener('input',()=>{showMode='all';renderChannels()});document.querySelector('#refreshBtn').onclick=loadAll;document.querySelector('#favoritesBtn').onclick=()=>{showMode=showMode==='favorites'?'all':'favorites';renderChannels()};document.querySelector('#recentBtn').onclick=()=>{showMode=showMode==='recent'?'all':'recent';renderChannels()};document.querySelector('#favoriteBtn').onclick=()=>{if(!activeChannel)return;favorites.has(activeChannel.id)?favorites.delete(activeChannel.id):favorites.add(activeChannel.id);localStorage.setItem('laxmanIptvFavorites',JSON.stringify([...favorites]));updateNow(activeChannel);renderChannels()};document.querySelector('#prevBtn').onclick=()=>moveChannel(-1);document.querySelector('#nextBtn').onclick=()=>moveChannel(1);document.querySelector('#pipBtn').onclick=async()=>{try{document.pictureInPictureElement?await document.exitPictureInPicture():await video.requestPictureInPicture()}catch(e){}};document.querySelector('#fullscreenBtn').onclick=()=>{document.fullscreenElement?document.exitFullscreen():document.querySelector('#playerShell').requestFullscreen?.()};document.querySelector('#themeBtn').onclick=()=>document.body.classList.toggle('light');
document.querySelectorAll('.mobile-nav button').forEach(b=>b.onclick=()=>{const n=b.dataset.nav;if(n==='top')scrollTo({top:0,behavior:'smooth'});if(n==='player')document.querySelector('#playerShell').scrollIntoView({behavior:'smooth'});if(n==='favorites'){showMode='favorites';renderChannels();document.querySelector('#channelList').scrollIntoView({behavior:'smooth'})}if(n==='categories')document.querySelector('#categories').scrollIntoView({behavior:'smooth'});document.querySelectorAll('.mobile-nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active')});
document.addEventListener('keydown',e=>{if(e.target.matches('input'))return;if(e.key==='ArrowDown')moveChannel(1);if(e.key==='ArrowUp')moveChannel(-1);if(e.key===' '){e.preventDefault();video.paused?video.play():video.pause()}if(e.key.toLowerCase()==='f')document.querySelector('#fullscreenBtn').click();if(e.key.toLowerCase()==='m')video.muted=!video.muted});
loadAll();