const PLAYLISTS=['Nepal.m3u','SPORT-IPTV-DECEMBER.m3u','Sonylive.m3u','Sonylivnew.m3u','Worldcup.m3u','india.m3u'];
const video=document.querySelector('#video'), list=document.querySelector('#channelList'), cats=document.querySelector('#categories'), search=document.querySelector('#searchInput');
const overlay=document.querySelector('#playerOverlay'), status=document.querySelector('#playerStatus');
let allChannels=[], activeCategory='all', activeChannel=null, hls=null;
const categoryName=f=>f.replace(/\.m3u$/i,'').replace(/[-_]+/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
function parseM3U(text,file){const lines=text.split(/\r?\n/);const out=[];for(let i=0;i<lines.length;i++){if(!lines[i].startsWith('#EXTINF'))continue;const info=lines[i];const url=(lines[i+1]||'').trim();if(!url||url.startsWith('#'))continue;const comma=info.indexOf(',');let name=comma>-1?info.slice(comma+1).trim():'Unknown Channel';const logo=(info.match(/tvg-logo="([^"]*)"/i)||[])[1]||'';const group=(info.match(/group-title="([^"]*)"/i)||[])[1]||categoryName(file);out.push({id:`${file}:${i}`,name,url,logo,group,source:file,category:categoryName(file)});}return out}
async function loadAll(){setLoading(true);try{const results=await Promise.all(PLAYLISTS.map(async file=>{const r=await fetch(file,{cache:'no-store'});if(!r.ok)throw new Error(file);return parseM3U(await r.text(),file)}));allChannels=results.flat();renderCategories();renderChannels();document.querySelector('#channelCount').textContent=allChannels.length;document.querySelector('#categoryCount').textContent=PLAYLISTS.length;}catch(e){list.innerHTML='<div class="empty">Could not load the playlists. Check GitHub Pages/CORS and the M3U files.</div>';console.error(e)}finally{setLoading(false)}}
function setLoading(on){if(on){list.innerHTML='<div class="empty">Loading all channels…</div>';document.querySelector('#visibleCount').textContent='Fetching playlists';}}
function renderCategories(){cats.innerHTML='';[['all','All Channels'],...PLAYLISTS.map(f=>[f,categoryName(f)])].forEach(([id,label])=>{const b=document.createElement('button');b.className=`cat ${activeCategory===id?'active':''}`;b.textContent=label;b.onclick=()=>{activeCategory=id;renderCategories();renderChannels()};cats.appendChild(b)})}
function getVisible(){const q=search.value.trim().toLowerCase();return allChannels.filter(c=>(activeCategory==='all'||c.source===activeCategory)&&( !q||c.name.toLowerCase().includes(q)||c.group.toLowerCase().includes(q)))}
function renderChannels(){const items=getVisible();document.querySelector('#listTitle').textContent=activeCategory==='all'?'All Channels':categoryName(activeCategory);document.querySelector('#visibleCount').textContent=`${items.length} channel${items.length===1?'':'s'}`;if(!items.length){list.innerHTML='<div class="empty">No channels found.</div>';return}const frag=document.createDocumentFragment();items.forEach(c=>{const b=document.createElement('button');b.className=`channel ${activeChannel?.id===c.id?'active':''}`;b.innerHTML=`${c.logo?`<img class="channel-logo" src="${esc(c.logo)}" alt="" loading="lazy" onerror="this.style.display='none'">`:'<div class="channel-logo fallback">TV</div>'}<div class="channel-info"><strong>${esc(c.name)}</strong><span>${esc(c.group||c.category)}</span></div>`;b.onclick=()=>play(c,b);frag.appendChild(b)});list.replaceChildren(frag)}
function esc(s){return String(s).replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]))}
function showOverlay(message,spin=true){overlay.classList.remove('hidden');status.textContent=message;overlay.querySelector('.spinner').style.display=spin?'block':'none'}
function play(c,button){activeChannel=c;document.querySelector('#nowTitle').textContent=c.name;document.querySelector('#nowMeta').textContent=`${c.category} · ${c.group||'Live stream'}`;document.querySelector('#nowAvatar').textContent=(c.name.match(/[A-Za-z0-9]/)?.[0]||'TV').toUpperCase();renderChannels();showOverlay('Connecting…',true);if(hls){hls.destroy();hls=null}video.pause();video.removeAttribute('src');video.load();if(window.Hls&&Hls.isSupported()){hls=new Hls({enableWorker:true,lowLatencyMode:true,maxBufferLength:20,backBufferLength:30,capLevelToPlayerSize:true});hls.loadSource(c.url);hls.attachMedia(video);hls.on(Hls.Events.MANIFEST_PARSED,()=>startPlayback());hls.on(Hls.Events.ERROR,(_,data)=>{if(data.fatal){showOverlay(data.type==='networkError'?'Stream unavailable':'Playback error',false);console.warn(data)}})}else if(video.canPlayType('application/vnd.apple.mpegurl')){video.src=c.url;video.addEventListener('loadedmetadata',startPlayback,{once:true})}else showOverlay('HLS is not supported in this browser',false)}
async function startPlayback(){try{await video.play();overlay.classList.add('hidden')}catch(e){status.textContent='Press play to start';overlay.querySelector('.spinner').style.display='none'}}
video.addEventListener('waiting',()=>{if(activeChannel)showOverlay('Buffering…',true)});video.addEventListener('playing',()=>overlay.classList.add('hidden'));video.addEventListener('error',()=>activeChannel&&showOverlay('Unable to play this stream',false));
search.addEventListener('input',renderChannels);document.querySelector('#refreshBtn').onclick=loadAll;document.querySelector('#pipBtn').onclick=async()=>{try{if(document.pictureInPictureElement)await document.exitPictureInPicture();else await video.requestPictureInPicture()}catch(e){}};document.querySelector('#fullscreenBtn').onclick=()=>{const el=document.querySelector('#playerShell');if(document.fullscreenElement)document.exitFullscreen();else el.requestFullscreen?.()};document.querySelector('#themeBtn').onclick=()=>document.body.classList.toggle('light');
loadAll();